let a = document.createElement('a');
a.style.width = '45px';
a.style.height = '45px';
a.style.position = 'fixed';
a.style.right = '10px';
a.style.bottom = '150px';
a.style.border = '1px solid #000';
a.style.borderRadius = '5px';
a.style.background = 'url("http://www.simperfect.com/images/icon_13.png") no-repeat center';
a.style.backgroundSize = '75%';
a.style.backgroundColor = '#fff';
a.setAttribute('href', 'http://www.simperfect.com');
a.setAttribute('target', '_blank');
a.setAttribute('title', '在线客服');
document.body.appendChild(a);